# ==============================================================================
# Merged Lakeflow Source: azure_devops
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime
from decimal import Decimal
from typing import (
    Any,
    Callable,
    Iterator,
    Sequence,
)
import json

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
import base64
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current start offset, or None on the first call.
                    PySpark's ``DataSourceStreamReader.latestOffset()`` does not
                    pass this yet, so the framework always sends None for now.
                    Connectors may use it to implement windowed batching when
                    called directly.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/azure_devops/azure_devops_schemas.py
    ########################################################

    PROJECT_STRUCT = StructType(
        [
            StructField("id", StringType(), True),
            StructField("name", StringType(), True),
            StructField("url", StringType(), True),
            StructField("state", StringType(), True),
            StructField("revision", LongType(), True),
            StructField("visibility", StringType(), True),
            StructField("lastUpdateTime", StringType(), True),
        ]
    )

    PARENT_REPOSITORY_STRUCT = StructType(
        [
            StructField("id", StringType(), True),
            StructField("name", StringType(), True),
            StructField("url", StringType(), True),
            StructField("project", PROJECT_STRUCT, True),
        ]
    )

    LINK_STRUCT = StructType([StructField("href", StringType(), True)])

    LINKS_STRUCT = StructType(
        [
            StructField("self", LINK_STRUCT, True),
            StructField("project", LINK_STRUCT, True),
            StructField("web", LINK_STRUCT, True),
            StructField("ssh", LINK_STRUCT, True),
            StructField("commits", LINK_STRUCT, True),
            StructField("refs", LINK_STRUCT, True),
            StructField("pullRequests", LINK_STRUCT, True),
            StructField("items", LINK_STRUCT, True),
            StructField("pushes", LINK_STRUCT, True),
        ]
    )

    IDENTITY_STRUCT = StructType(
        [
            StructField("id", StringType(), True),
            StructField("displayName", StringType(), True),
            StructField("uniqueName", StringType(), True),
            StructField("url", StringType(), True),
            StructField("imageUrl", StringType(), True),
        ]
    )

    GIT_USER_STRUCT = StructType(
        [
            StructField("name", StringType(), True),
            StructField("email", StringType(), True),
            StructField("date", StringType(), True),
        ]
    )

    CHANGE_COUNTS_STRUCT = StructType(
        [
            StructField("Add", IntegerType(), True),
            StructField("Edit", IntegerType(), True),
            StructField("Delete", IntegerType(), True),
        ]
    )

    COMMIT_REF_STRUCT = StructType(
        [
            StructField("commitId", StringType(), True),
            StructField("url", StringType(), True),
        ]
    )

    REF_UPDATE_STRUCT = StructType(
        [
            StructField("name", StringType(), True),
            StructField("oldObjectId", StringType(), True),
            StructField("newObjectId", StringType(), True),
        ]
    )

    COMMENT_STRUCT = StructType(
        [
            StructField("id", LongType(), True),
            StructField("parentCommentId", LongType(), True),
            StructField("author", IDENTITY_STRUCT, True),
            StructField("content", StringType(), True),
            StructField("publishedDate", StringType(), True),
            StructField("lastUpdatedDate", StringType(), True),
            StructField("lastContentUpdatedDate", StringType(), True),
            StructField("commentType", StringType(), True),
        ]
    )

    POSITION_STRUCT = StructType(
        [
            StructField("line", LongType(), True),
            StructField("offset", LongType(), True),
        ]
    )

    THREAD_CONTEXT_STRUCT = StructType(
        [
            StructField("filePath", StringType(), True),
            StructField("rightFileStart", POSITION_STRUCT, True),
            StructField("rightFileEnd", POSITION_STRUCT, True),
            StructField("leftFileStart", POSITION_STRUCT, True),
            StructField("leftFileEnd", POSITION_STRUCT, True),
        ]
    )

    RELATION_STRUCT = StructType(
        [
            StructField("rel", StringType(), True),
            StructField("url", StringType(), True),
        ]
    )

    FIELD_DEF_STRUCT = StructType(
        [
            StructField("referenceName", StringType(), True),
            StructField("name", StringType(), True),
            StructField("type", StringType(), True),
            StructField("readOnly", BooleanType(), True),
            StructField("required", BooleanType(), True),
            StructField("defaultValue", StringType(), True),
            StructField("helpText", StringType(), True),
        ]
    )

    STATE_STRUCT = StructType(
        [
            StructField("name", StringType(), True),
            StructField("color", StringType(), True),
            StructField("category", StringType(), True),
        ]
    )

    ICON_STRUCT = StructType(
        [
            StructField("id", StringType(), True),
            StructField("url", StringType(), True),
        ]
    )


    # =============================================================================
    # Table Schemas
    # =============================================================================

    TABLE_SCHEMAS: dict[str, StructType] = {
        "projects": StructType(
            [
                StructField("id", StringType(), False),
                StructField("name", StringType(), True),
                StructField("description", StringType(), True),
                StructField("url", StringType(), True),
                StructField("state", StringType(), True),
                StructField("revision", LongType(), True),
                StructField("visibility", StringType(), True),
                StructField("lastUpdateTime", StringType(), True),
                StructField("organization", StringType(), False),
            ]
        ),
        "repositories": StructType(
            [
                StructField("id", StringType(), False),
                StructField("name", StringType(), True),
                StructField("url", StringType(), True),
                StructField("project", PROJECT_STRUCT, True),
                StructField("defaultBranch", StringType(), True),
                StructField("size", LongType(), True),
                StructField("remoteUrl", StringType(), True),
                StructField("sshUrl", StringType(), True),
                StructField("webUrl", StringType(), True),
                StructField("isDisabled", BooleanType(), True),
                StructField("isInMaintenance", BooleanType(), True),
                StructField("isFork", BooleanType(), True),
                StructField(
                    "parentRepository", PARENT_REPOSITORY_STRUCT, True
                ),
                StructField("_links", LINKS_STRUCT, True),
                StructField("organization", StringType(), False),
                StructField("project_name", StringType(), False),
            ]
        ),
        "commits": StructType(
            [
                StructField("commitId", StringType(), False),
                StructField("author", GIT_USER_STRUCT, True),
                StructField("committer", GIT_USER_STRUCT, True),
                StructField("comment", StringType(), True),
                StructField("commentTruncated", BooleanType(), True),
                StructField("changeCounts", CHANGE_COUNTS_STRUCT, True),
                StructField("url", StringType(), True),
                StructField("remoteUrl", StringType(), True),
                StructField("treeId", StringType(), True),
                StructField("parents", ArrayType(StringType()), True),
                StructField("organization", StringType(), False),
                StructField("project_name", StringType(), False),
                StructField("repository_id", StringType(), False),
            ]
        ),
        "pullrequests": StructType(
            [
                StructField("pullRequestId", LongType(), False),
                StructField("codeReviewId", LongType(), True),
                StructField("status", StringType(), True),
                StructField("createdBy", IDENTITY_STRUCT, True),
                StructField("creationDate", StringType(), True),
                StructField("closedDate", StringType(), True),
                StructField("title", StringType(), True),
                StructField("description", StringType(), True),
                StructField("sourceRefName", StringType(), True),
                StructField("targetRefName", StringType(), True),
                StructField("mergeStatus", StringType(), True),
                StructField("mergeId", StringType(), True),
                StructField(
                    "lastMergeSourceCommit", COMMIT_REF_STRUCT, True
                ),
                StructField(
                    "lastMergeTargetCommit", COMMIT_REF_STRUCT, True
                ),
                StructField("lastMergeCommit", COMMIT_REF_STRUCT, True),
                StructField("url", StringType(), True),
                StructField("supportsIterations", BooleanType(), True),
                StructField("artifactId", StringType(), True),
                StructField("organization", StringType(), False),
                StructField("project_name", StringType(), False),
                StructField("repository_id", StringType(), False),
            ]
        ),
        "refs": StructType(
            [
                StructField("name", StringType(), False),
                StructField("objectId", StringType(), True),
                StructField("creator", IDENTITY_STRUCT, True),
                StructField("url", StringType(), True),
                StructField("peeledObjectId", StringType(), True),
                StructField("organization", StringType(), False),
                StructField("project_name", StringType(), False),
                StructField("repository_id", StringType(), False),
            ]
        ),
        "pushes": StructType(
            [
                StructField("pushId", LongType(), False),
                StructField("date", StringType(), True),
                StructField("pushedBy", IDENTITY_STRUCT, True),
                StructField("url", StringType(), True),
                StructField(
                    "refUpdates", ArrayType(REF_UPDATE_STRUCT), True
                ),
                StructField("organization", StringType(), False),
                StructField("project_name", StringType(), False),
                StructField("repository_id", StringType(), False),
            ]
        ),
        "users": StructType(
            [
                StructField("descriptor", StringType(), False),
                StructField("displayName", StringType(), True),
                StructField("mailAddress", StringType(), True),
                StructField("principalName", StringType(), True),
                StructField("origin", StringType(), True),
                StructField("originId", StringType(), True),
                StructField("subjectKind", StringType(), True),
                StructField("domain", StringType(), True),
                StructField("directoryAlias", StringType(), True),
                StructField("url", StringType(), True),
                StructField("_links", LINKS_STRUCT, True),
                StructField("organization", StringType(), False),
            ]
        ),
        "pullrequest_threads": StructType(
            [
                StructField("id", LongType(), False),
                StructField("publishedDate", StringType(), True),
                StructField("lastUpdatedDate", StringType(), True),
                StructField(
                    "comments", ArrayType(COMMENT_STRUCT), True
                ),
                StructField("status", StringType(), True),
                StructField(
                    "threadContext", THREAD_CONTEXT_STRUCT, True
                ),
                StructField("isDeleted", BooleanType(), True),
                StructField("organization", StringType(), False),
                StructField("project_name", StringType(), False),
                StructField("repository_id", StringType(), False),
                StructField("pullrequest_id", LongType(), False),
            ]
        ),
        "pullrequest_workitems": StructType(
            [
                StructField("id", StringType(), False),
                StructField("url", StringType(), True),
                StructField("organization", StringType(), False),
                StructField("project_name", StringType(), False),
                StructField("repository_id", StringType(), False),
                StructField("pullrequest_id", LongType(), False),
            ]
        ),
        "pullrequest_commits": StructType(
            [
                StructField("commitId", StringType(), False),
                StructField("author", GIT_USER_STRUCT, True),
                StructField("committer", GIT_USER_STRUCT, True),
                StructField("comment", StringType(), True),
                StructField("commentTruncated", BooleanType(), True),
                StructField("url", StringType(), True),
                StructField("organization", StringType(), False),
                StructField("project_name", StringType(), False),
                StructField("repository_id", StringType(), False),
                StructField("pullrequest_id", LongType(), False),
            ]
        ),
        "pullrequest_reviewers": StructType(
            [
                StructField("reviewerUrl", StringType(), True),
                StructField("vote", LongType(), True),
                StructField("hasDeclined", BooleanType(), True),
                StructField("isFlagged", BooleanType(), True),
                StructField("displayName", StringType(), True),
                StructField("id", StringType(), False),
                StructField("uniqueName", StringType(), True),
                StructField("url", StringType(), True),
                StructField("imageUrl", StringType(), True),
                StructField("isRequired", BooleanType(), True),
                StructField("organization", StringType(), False),
                StructField("project_name", StringType(), False),
                StructField("repository_id", StringType(), False),
                StructField("pullrequest_id", LongType(), False),
            ]
        ),
        "workitems": StructType(
            [
                StructField("id", LongType(), False),
                StructField("rev", LongType(), True),
                StructField("fields", StringType(), True),
                StructField(
                    "relations", ArrayType(RELATION_STRUCT), True
                ),
                StructField("url", StringType(), True),
                StructField("organization", StringType(), False),
                StructField("project_name", StringType(), False),
            ]
        ),
        "workitem_revisions": StructType(
            [
                StructField("id", LongType(), False),
                StructField("rev", LongType(), False),
                StructField("workItemId", LongType(), True),
                StructField("revisedDate", StringType(), True),
                StructField("fields", StringType(), True),
                StructField("url", StringType(), True),
                StructField("organization", StringType(), False),
                StructField("project_name", StringType(), False),
            ]
        ),
        "workitem_types": StructType(
            [
                StructField("name", StringType(), True),
                StructField("referenceName", StringType(), False),
                StructField("description", StringType(), True),
                StructField("color", StringType(), True),
                StructField("icon", ICON_STRUCT, True),
                StructField("isDisabled", BooleanType(), True),
                StructField(
                    "fields", ArrayType(FIELD_DEF_STRUCT), True
                ),
                StructField(
                    "states", ArrayType(STATE_STRUCT), True
                ),
                StructField("url", StringType(), True),
                StructField("organization", StringType(), False),
                StructField("project_name", StringType(), False),
            ]
        ),
    }


    # =============================================================================
    # Table Metadata
    # =============================================================================

    TABLE_METADATA: dict[str, dict] = {
        "projects": {
            "primary_keys": ["id"],
            "ingestion_type": "snapshot",
        },
        "repositories": {
            "primary_keys": ["id"],
            "ingestion_type": "snapshot",
        },
        "commits": {
            "primary_keys": ["commitId", "repository_id"],
            "ingestion_type": "append",
        },
        "pullrequests": {
            "primary_keys": ["pullRequestId", "repository_id"],
            "cursor_field": "closedDate",
            "ingestion_type": "cdc",
        },
        "refs": {
            "primary_keys": ["name", "repository_id"],
            "ingestion_type": "snapshot",
        },
        "pushes": {
            "primary_keys": ["pushId", "repository_id"],
            "ingestion_type": "append",
        },
        "users": {
            "primary_keys": ["descriptor"],
            "ingestion_type": "snapshot",
        },
        "pullrequest_threads": {
            "primary_keys": ["id", "pullrequest_id", "repository_id"],
            "ingestion_type": "append",
            "cursor_field": "publishedDate",
        },
        "pullrequest_workitems": {
            "primary_keys": ["id", "pullrequest_id", "repository_id"],
            "ingestion_type": "snapshot",
        },
        "pullrequest_commits": {
            "primary_keys": [
                "commitId", "pullrequest_id", "repository_id",
            ],
            "ingestion_type": "snapshot",
        },
        "pullrequest_reviewers": {
            "primary_keys": ["id", "pullrequest_id", "repository_id"],
            "ingestion_type": "snapshot",
        },
        "workitems": {
            "primary_keys": ["id"],
            "ingestion_type": "cdc",
            "cursor_field": "rev",
        },
        "workitem_revisions": {
            "primary_keys": ["id", "rev"],
            "ingestion_type": "append",
        },
        "workitem_types": {
            "primary_keys": ["referenceName", "project_name"],
            "ingestion_type": "snapshot",
        },
    }

    SUPPORTED_TABLES: list[str] = list(TABLE_SCHEMAS.keys())


    ########################################################
    # src/databricks/labs/community_connector/sources/azure_devops/azure_devops_utils.py
    ########################################################

    def api_get(
        session: requests.Session,
        url: str,
        params: dict[str, str],
        label: str,
    ) -> dict:
        """Make a GET request and return the parsed JSON response.

        Raises RuntimeError on non-200 status codes with a descriptive
        message that includes *label* (e.g. ``"commits"``).
        """
        response = session.get(url, params=params, timeout=30)
        if response.status_code != 200:
            raise RuntimeError(
                f"Azure DevOps API error for {label}: "
                f"{response.status_code} {response.text}"
            )
        return response.json()


    def api_get_list(
        session: requests.Session,
        url: str,
        params: dict[str, str],
        label: str,
        key: str = "value",
    ) -> list[dict]:
        """GET a list endpoint and return the ``value`` array."""
        data = api_get(session, url, params, label)
        return data.get(key, [])


    def resolve_projects(
        session: requests.Session,
        base_url: str,
        project: str | None,
    ) -> list[str]:
        """Return a list of project names to iterate over.

        If *project* is given, return it as a single-element list.
        Otherwise fetch all projects from the organization.
        """
        if project:
            return [project]
        items = api_get_list(
            session,
            f"{base_url}/_apis/projects",
            {"api-version": "7.1"},
            "projects",
        )
        return [p["name"] for p in items if p.get("name")]


    def fetch_repos(
        session: requests.Session,
        base_url: str,
        project: str,
    ) -> list[dict]:
        """Fetch all repositories for a single project."""
        return api_get_list(
            session,
            f"{base_url}/{project}/_apis/git/repositories",
            {"api-version": "7.1"},
            "repositories",
        )


    def fetch_prs(
        session: requests.Session,
        base_url: str,
        project: str,
        repo_id: str,
    ) -> list[dict]:
        """Fetch all pull requests (all statuses) for a repo."""
        url = (
            f"{base_url}/{project}/_apis/git/repositories"
            f"/{repo_id}/pullrequests"
        )
        return api_get_list(
            session,
            url,
            {"api-version": "7.1", "searchCriteria.status": "all"},
            "pullrequests",
        )


    def nullify_empty(record: dict, *keys: str) -> None:
        """Replace missing or empty-dict nested structs with ``None``."""
        for key in keys:
            if key not in record or record[key] == {}:
                record[key] = None


    # --------------------------------------------------------------------------- #
    # PR sub-resource auto-discovery helper
    # --------------------------------------------------------------------------- #

    def for_each_pr(
        session: requests.Session,
        base_url: str,
        projects: list[str],
        table_options: dict[str, str],
        callback: Callable[
            [str, str, int], list[dict[str, Any]]
        ],
    ) -> list[dict[str, Any]]:
        """Iterate over pull requests and collect records via *callback*.

        The three-tier auto-discovery pattern used by threads, work-items,
        commits, and reviewers tables:

        1. If ``repository_id`` **and** ``pullrequest_id`` are in
           *table_options* → call *callback* once.
        2. If only ``repository_id`` → iterate all PRs in that repo.
        3. If neither → iterate all repos in each project, then all PRs.

        *callback(project, repo_id, pr_id)* must return a list of enriched
        record dicts for that single PR.
        """
        repo_id = table_options.get("repository_id")
        pr_id = table_options.get("pullrequest_id")

        all_records: list[dict[str, Any]] = []

        for project in projects:
            if repo_id and pr_id:
                all_records.extend(
                    callback(project, repo_id, int(pr_id))
                )
            else:
                target_ids = (
                    [repo_id] if repo_id
                    else [r["id"] for r in
                          fetch_repos(session, base_url, project)
                          if r.get("id")]
                )
                for rid in target_ids:
                    try:
                        prs = fetch_prs(
                            session, base_url, project, rid
                        )
                    except RuntimeError:
                        continue
                    for pr in prs:
                        pid = pr.get("pullRequestId")
                        if pid is None:
                            continue
                        try:
                            all_records.extend(
                                callback(project, rid, pid)
                            )
                        except RuntimeError:
                            continue

        return all_records


    ########################################################
    # src/databricks/labs/community_connector/sources/azure_devops/azure_devops.py
    ########################################################

    class AzureDevopsLakeflowConnect(LakeflowConnect):
        def __init__(self, options: dict[str, str]) -> None:
            """Initialize the Azure DevOps connector.

            Expected options:
                - organization: Azure DevOps organization name.
                - project: Project name or ID (optional).
                - personal_access_token: PAT for authentication.
            """
            organization = options.get("organization")
            project = options.get("project")
            personal_access_token = options.get("personal_access_token")

            if not organization:
                raise ValueError(
                    "Azure DevOps connector requires 'organization'"
                )
            if not personal_access_token:
                raise ValueError(
                    "Azure DevOps connector requires 'personal_access_token'"
                )

            self.organization = organization
            self.project = project
            self.base_url = f"https://dev.azure.com/{organization}"
            self.vssps_base_url = (
                f"https://vssps.dev.azure.com/{organization}"
            )

            auth_b64 = base64.b64encode(
                f":{personal_access_token}".encode("ascii")
            ).decode("ascii")

            self._session = requests.Session()
            self._session.headers.update(
                {
                    "Authorization": f"Basic {auth_b64}",
                    "Accept": "application/json",
                }
            )

        # ------------------------------------------------------------------ #
        # Interface methods
        # ------------------------------------------------------------------ #

        def list_tables(self) -> list[str]:
            return SUPPORTED_TABLES

        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            if table_name not in TABLE_SCHEMAS:
                raise ValueError(f"Unsupported table: {table_name!r}")
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            if table_name not in TABLE_METADATA:
                raise ValueError(f"Unsupported table: {table_name!r}")
            return TABLE_METADATA[table_name]

        def read_table(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            dispatch = {
                "projects": self._read_projects,
                "repositories": self._read_repositories,
                "commits": self._read_commits,
                "pullrequests": self._read_pullrequests,
                "refs": self._read_refs,
                "pushes": self._read_pushes,
                "users": self._read_users,
                "pullrequest_threads": self._read_pullrequest_threads,
                "pullrequest_workitems": self._read_pr_workitems,
                "pullrequest_commits": self._read_pr_commits,
                "pullrequest_reviewers": self._read_pr_reviewers,
                "workitems": self._read_workitems,
                "workitem_revisions": self._read_workitem_revisions,
                "workitem_types": self._read_workitem_types,
            }
            handler = dispatch.get(table_name)
            if handler is None:
                raise ValueError(f"Unsupported table: {table_name!r}")
            return handler(start_offset, table_options)

        # ------------------------------------------------------------------ #
        # Helper: resolve project
        # ------------------------------------------------------------------ #

        def _resolve_project(
            self, table_options: dict[str, str]
        ) -> str | None:
            return table_options.get("project") or self.project

        def _resolve_projects(
            self, table_options: dict[str, str]
        ) -> list[str]:
            return resolve_projects(
                self._session,
                self.base_url,
                self._resolve_project(table_options),
            )

        # ------------------------------------------------------------------ #
        # Helper: iterate over all repos
        # ------------------------------------------------------------------ #

        def _for_all_repos(
            self,
            start_offset: dict,
            table_options: dict[str, str],
            reader,
        ) -> tuple[Iterator[dict], dict]:
            """Call *reader* for every repo across projects."""
            repos_iter, _ = self._read_repositories({}, {})
            all_records: list[dict[str, Any]] = []
            for repo in repos_iter:
                repo_id = repo.get("id")
                proj = repo.get("project_name")
                if not repo_id or not proj:
                    continue
                opts = {**table_options, "repository_id": repo_id, "project": proj}
                try:
                    records_iter, _ = reader(start_offset, opts)
                    all_records.extend(records_iter)
                except Exception:  # pylint: disable=broad-except
                    continue
            return iter(all_records), {}

        # ------------------------------------------------------------------ #
        # Table readers
        # ------------------------------------------------------------------ #

        def _read_projects(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            projects = api_get_list(
                self._session,
                f"{self.base_url}/_apis/projects",
                {"api-version": "7.1"},
                "projects",
            )
            records = []
            for p in projects:
                rec = dict(p)
                rec["organization"] = self.organization
                records.append(rec)
            return iter(records), {}

        def _read_repositories(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            project = self._resolve_project(table_options)
            if not project:
                return self._read_repos_all_projects(table_options)

            repos = api_get_list(
                self._session,
                f"{self.base_url}/{project}/_apis/git/repositories",
                {
                    "api-version": "7.1",
                    "includeLinks": "true",
                    "includeAllUrls": "true",
                },
                "repositories",
            )
            records = []
            for r in repos:
                rec = dict(r)
                rec["organization"] = self.organization
                rec["project_name"] = project
                nullify_empty(rec, "parentRepository", "project", "_links")
                records.append(rec)
            return iter(records), {}

        def _read_repos_all_projects(
            self, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            projects_iter, _ = self._read_projects({}, {})
            all_records: list[dict[str, Any]] = []
            for p in projects_iter:
                name = p.get("name")
                if not name:
                    continue
                try:
                    opts = {**table_options, "project": name}
                    it, _ = self._read_repositories({}, opts)
                    all_records.extend(it)
                except Exception:  # pylint: disable=broad-except
                    continue
            return iter(all_records), {}

        # -- Git objects (commits, PRs, refs, pushes) ---------------------- #

        def _read_commits(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            repo_id = table_options.get("repository_id")
            if not repo_id:
                return self._for_all_repos(
                    start_offset, table_options, self._read_commits
                )

            project = self._resolve_project(table_options)
            if not project:
                raise ValueError(
                    "Project must be specified when repository_id is provided"
                )

            skip = (start_offset or {}).get("skip", 0)
            top = 1000
            url = (
                f"{self.base_url}/{project}/_apis/git/repositories"
                f"/{repo_id}/commits"
            )
            commits = api_get_list(
                self._session, url,
                {"api-version": "7.1", "$top": str(top), "$skip": str(skip)},
                "commits",
            )

            records = []
            for c in commits:
                rec = dict(c)
                rec["organization"] = self.organization
                rec["project_name"] = project
                rec["repository_id"] = repo_id
                nullify_empty(rec, "author", "committer", "changeCounts")
                records.append(rec)

            new_offset = {"skip": skip + top} if len(commits) == top else {}
            return iter(records), new_offset

        def _read_pullrequests(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            repo_id = table_options.get("repository_id")
            if not repo_id:
                return self._for_all_repos(
                    start_offset, table_options, self._read_pullrequests
                )

            project = self._resolve_project(table_options)
            if not project:
                raise ValueError(
                    "Project must be specified when repository_id is provided"
                )

            status_filter = table_options.get("status_filter", "all")
            url = (
                f"{self.base_url}/{project}/_apis/git/repositories"
                f"/{repo_id}/pullrequests"
            )
            prs = api_get_list(
                self._session, url,
                {"api-version": "7.1", "searchCriteria.status": status_filter},
                "pullrequests",
            )

            records = []
            for pr in prs:
                rec = dict(pr)
                rec["organization"] = self.organization
                rec["project_name"] = project
                rec["repository_id"] = repo_id
                nullify_empty(
                    rec, "createdBy",
                    "lastMergeSourceCommit", "lastMergeTargetCommit",
                    "lastMergeCommit",
                )
                records.append(rec)
            return iter(records), {}

        def _read_refs(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            repo_id = table_options.get("repository_id")
            if not repo_id:
                return self._for_all_repos(
                    start_offset, table_options, self._read_refs
                )

            project = self._resolve_project(table_options)
            if not project:
                raise ValueError(
                    "Project must be specified when repository_id is provided"
                )

            url = (
                f"{self.base_url}/{project}/_apis/git/repositories"
                f"/{repo_id}/refs"
            )
            params: dict[str, str] = {"api-version": "7.1"}
            ref_filter = table_options.get("filter")
            if ref_filter:
                params["filter"] = ref_filter

            refs = api_get_list(
                self._session, url, params, "refs"
            )

            records = []
            for ref in refs:
                rec = dict(ref)
                rec["organization"] = self.organization
                rec["project_name"] = project
                rec["repository_id"] = repo_id
                nullify_empty(rec, "creator")
                records.append(rec)
            return iter(records), {}

        def _read_pushes(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            repo_id = table_options.get("repository_id")
            if not repo_id:
                return self._for_all_repos(
                    start_offset, table_options, self._read_pushes
                )

            project = self._resolve_project(table_options)
            if not project:
                raise ValueError(
                    "Project must be specified when repository_id is provided"
                )

            skip = (start_offset or {}).get("skip", 0)
            top = 1000
            url = (
                f"{self.base_url}/{project}/_apis/git/repositories"
                f"/{repo_id}/pushes"
            )
            pushes = api_get_list(
                self._session, url,
                {"api-version": "7.1", "$top": str(top), "$skip": str(skip)},
                "pushes",
            )

            records = []
            for push in pushes:
                rec = dict(push)
                rec["organization"] = self.organization
                rec["project_name"] = project
                rec["repository_id"] = repo_id
                nullify_empty(rec, "pushedBy")
                records.append(rec)

            new_offset = {"skip": skip + top} if len(pushes) == top else {}
            return iter(records), new_offset

        # -- Users --------------------------------------------------------- #

        def _read_users(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            url = f"{self.vssps_base_url}/_apis/graph/users"
            params: dict[str, str] = {"api-version": "7.1-preview.1"}

            token = (start_offset or {}).get("continuationToken")
            if token:
                params["continuationToken"] = token

            response = self._session.get(url, params=params, timeout=30)
            if response.status_code != 200:
                raise RuntimeError(
                    f"Azure DevOps API error for users: "
                    f"{response.status_code} {response.text}"
                )

            users = response.json().get("value", [])
            records = []
            for u in users:
                rec = dict(u)
                rec["organization"] = self.organization
                nullify_empty(rec, "_links")
                records.append(rec)

            new_offset: dict[str, str] = {}
            next_token = response.headers.get("X-MS-ContinuationToken")
            if next_token:
                new_offset["continuationToken"] = next_token
            return iter(records), new_offset

        # -- PR sub-resources (threads, workitems, commits, reviewers) ----- #

        def _read_pullrequest_threads(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            projects = self._resolve_projects(table_options)

            def _fetch(project: str, repo_id: str, pr_id: int):
                url = (
                    f"{self.base_url}/{project}/_apis/git/repositories"
                    f"/{repo_id}/pullRequests/{pr_id}/threads"
                )
                threads = api_get_list(
                    self._session, url,
                    {"api-version": "7.1"}, "pullrequest_threads",
                )
                results = []
                for t in threads:
                    rec = dict(t)
                    rec["organization"] = self.organization
                    rec["project_name"] = project
                    rec["repository_id"] = repo_id
                    rec["pullrequest_id"] = pr_id
                    results.append(rec)
                return results

            records = for_each_pr(
                self._session, self.base_url,
                projects, table_options, _fetch,
            )
            return iter(records), {}

        def _read_pr_workitems(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            projects = self._resolve_projects(table_options)

            def _fetch(project: str, repo_id: str, pr_id: int):
                url = (
                    f"{self.base_url}/{project}/_apis/git/repositories"
                    f"/{repo_id}/pullRequests/{pr_id}/workitems"
                )
                items = api_get_list(
                    self._session, url,
                    {"api-version": "7.1"}, "pullrequest_workitems",
                )
                results = []
                for item in items:
                    rec = dict(item)
                    rec["organization"] = self.organization
                    rec["project_name"] = project
                    rec["repository_id"] = repo_id
                    rec["pullrequest_id"] = pr_id
                    results.append(rec)
                return results

            records = for_each_pr(
                self._session, self.base_url,
                projects, table_options, _fetch,
            )
            return iter(records), {}

        def _read_pr_commits(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            projects = self._resolve_projects(table_options)

            def _fetch(project: str, repo_id: str, pr_id: int):
                url = (
                    f"{self.base_url}/{project}/_apis/git/repositories"
                    f"/{repo_id}/pullRequests/{pr_id}/commits"
                )
                commits = api_get_list(
                    self._session, url,
                    {"api-version": "7.1"}, "pullrequest_commits",
                )
                results = []
                for c in commits:
                    rec = dict(c)
                    rec["organization"] = self.organization
                    rec["project_name"] = project
                    rec["repository_id"] = repo_id
                    rec["pullrequest_id"] = pr_id
                    results.append(rec)
                return results

            records = for_each_pr(
                self._session, self.base_url,
                projects, table_options, _fetch,
            )
            return iter(records), {}

        def _read_pr_reviewers(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            projects = self._resolve_projects(table_options)

            def _fetch(project: str, repo_id: str, pr_id: int):
                url = (
                    f"{self.base_url}/{project}/_apis/git/repositories"
                    f"/{repo_id}/pullRequests/{pr_id}/reviewers"
                )
                reviewers = api_get_list(
                    self._session, url,
                    {"api-version": "7.1"}, "pullrequest_reviewers",
                )
                results = []
                for r in reviewers:
                    rec = dict(r)
                    rec["organization"] = self.organization
                    rec["project_name"] = project
                    rec["repository_id"] = repo_id
                    rec["pullrequest_id"] = pr_id
                    results.append(rec)
                return results

            records = for_each_pr(
                self._session, self.base_url,
                projects, table_options, _fetch,
            )
            return iter(records), {}

        # -- Work items ---------------------------------------------------- #

        def _read_workitems(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            ids = table_options.get("ids")
            projects = self._resolve_projects(table_options)
            all_records: list[dict[str, Any]] = []

            for project in projects:
                if not ids:
                    ids_to_fetch = self._discover_workitem_ids(project)
                    if not ids_to_fetch:
                        continue
                else:
                    ids_to_fetch = ids

                url = f"{self.base_url}/{project}/_apis/wit/workitems"
                items = api_get_list(
                    self._session, url,
                    {
                        "api-version": "7.1",
                        "ids": ids_to_fetch,
                        "$expand": "relations",
                    },
                    "workitems",
                )
                for item in items:
                    rec = dict(item)
                    rec["organization"] = self.organization
                    rec["project_name"] = project
                    if "fields" in rec and isinstance(rec["fields"], dict):
                        rec["fields"] = json.dumps(rec["fields"])
                    all_records.append(rec)

            return iter(all_records), {}

        def _discover_workitem_ids(self, project: str) -> str | None:
            """Use WIQL to discover all work item IDs in a project."""
            url = f"{self.base_url}/{project}/_apis/wit/wiql"
            response = self._session.post(
                url,
                json={"query": "SELECT [System.Id] FROM WorkItems"},
                params={"api-version": "7.1"},
                timeout=30,
            )
            if response.status_code != 200:
                return None
            refs = response.json().get("workItems", [])
            if not refs:
                return None
            return ",".join(
                str(r["id"]) for r in refs if r.get("id")
            )

        def _read_workitem_revisions(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            projects = self._resolve_projects(table_options)
            all_records: list[dict[str, Any]] = []

            for project in projects:
                url = (
                    f"{self.base_url}/{project}"
                    "/_apis/wit/reporting/workitemrevisions"
                )
                params: dict[str, str] = {
                    "api-version": "7.1",
                    "includeDeleted": "true",
                }
                token = (start_offset or {}).get("continuationToken")
                if token:
                    params["continuationToken"] = token

                data = api_get(
                    self._session, url, params, "workitem_revisions"
                )
                for rev in data.get("values", []):
                    rec = dict(rev)
                    rec["organization"] = self.organization
                    rec["project_name"] = project
                    if "fields" in rec and isinstance(rec["fields"], dict):
                        rec["fields"] = json.dumps(rec["fields"])
                    all_records.append(rec)

                next_token = data.get("continuationToken")
                if next_token:
                    return iter(all_records), {
                        "continuationToken": next_token
                    }

            return iter(all_records), {}

        def _read_workitem_types(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            projects = self._resolve_projects(table_options)
            all_records: list[dict[str, Any]] = []

            for project in projects:
                url = (
                    f"{self.base_url}/{project}"
                    "/_apis/wit/workitemtypes"
                )
                types = api_get_list(
                    self._session, url,
                    {"api-version": "7.1"}, "workitem_types",
                )
                for wt in types:
                    rec = dict(wt)
                    rec["organization"] = self.organization
                    rec["project_name"] = project
                    all_records.append(rec)

            return iter(all_records), {}


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = AzureDevopsLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"


    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]


    class LakeflowPartitionedStreamReader(DataSourceStreamReader):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def latestOffset(self):
            # PySpark does not pass the current offset to latestOffset() yet,
            # so we forward None.  Once PySpark supports it, pass the real value.
            return self.lakeflow_connect.latest_offset(self.table_name, self.table_options, None)

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name != METADATA_TABLE:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        """
        PySpark DataSource implementation for Lakeflow Connect.
        """

        def __init__(self, options):
            self.options = options
            # TEMPORARY: LakeflowConnectImpl is replaced with the actual implementation
            # class during merge. See the placeholder comment at the top of this file.
            self.lakeflow_connect = LakeflowConnectImpl(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
