# ==============================================================================
# Merged Lakeflow Source: medidata_etmf
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime
from decimal import Decimal
from io import BytesIO
from typing import Any, Iterator, Sequence
import json
import re
import time

from mauth_client.requests_mauth import MAuth
from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
import base64
import pandas as pd
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current start offset, or None on the first call.
                    PySpark's ``DataSourceStreamReader.latestOffset()`` does not
                    pass this yet, so the framework always sends None for now.
                    Connectors may use it to implement windowed batching when
                    called directly.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/medidata_etmf/medidata_etmf.py
    ########################################################

    RETRIABLE_STATUS_CODES = {408, 429, 500, 502, 503}
    MAX_RETRIES = 5
    INITIAL_BACKOFF = 2.0
    DEFAULT_BASE_URL = "https://api.mdsol.com"
    DEFAULT_PAGE_SIZE = 1000
    REQUEST_TIMEOUT = 120

    REPORT_NAME_PATTERN = re.compile(
        r"(All Studies_KPI Rejections|.*_KPI Full Details|.*_KPI Total Filed Docs)",
        re.IGNORECASE,
    )

    REPORT_TYPE_TO_TABLE = {
        "eTMF Document Full Details": "etmf_full_details",
        "eTMF Filed Documents": "etmf_filed_docs",
        "Rejections": "etmf_rejections",
    }

    TABLE_TO_REPORT_TYPE = {v: k for k, v in REPORT_TYPE_TO_TABLE.items()}

    SUPPORTED_TABLES = ["etmf_full_details", "etmf_filed_docs", "etmf_rejections"]

    # ---------------------------------------------------------------------------
    # Static schemas — all string since data comes from Excel with dtype=str
    # ---------------------------------------------------------------------------

    FULL_DETAILS_COLUMN_MAP = {
        "Document Identifier": "document_id",
        "Level": "level",
        "Study": "study",
        "Environment": "environment",
        "Site": "site",
        "Folder Path": "folder_path",
        "Zone": "zone",
        "Artifact #": "artifact",
        "Name": "name",
        "Version": "version",
        "State": "state",
        "WF Type": "wf_type",
        "Initiator": "initiator",
        "Created On (User)": "created_by",
        "Edit Completed / Rejected By": "edit_completed_rejected_by",
        "Created On (Date/Time)": "created_at",
        "Document Property: Document Date": "document_date",
    }

    ETMF_FULL_DETAILS_SCHEMA = StructType(
        [
            StructField("document_id", StringType(), nullable=True),
            StructField("fsi_uuid", StringType(), nullable=True),
            StructField("level", StringType(), nullable=True),
            StructField("study", StringType(), nullable=True),
            StructField("environment", StringType(), nullable=True),
            StructField("site", StringType(), nullable=True),
            StructField("folder_path", StringType(), nullable=True),
            StructField("zone", StringType(), nullable=True),
            StructField("artifact", StringType(), nullable=True),
            StructField("name", StringType(), nullable=True),
            StructField("version", StringType(), nullable=True),
            StructField("state", StringType(), nullable=True),
            StructField("wf_type", StringType(), nullable=True),
            StructField("initiator", StringType(), nullable=True),
            StructField("created_by", StringType(), nullable=True),
            StructField("edit_completed_rejected_by", StringType(), nullable=True),
            StructField("created_at", StringType(), nullable=True),
            StructField("document_date", StringType(), nullable=True),
        ]
    )

    ETMF_FILED_DOCS_SCHEMA = StructType(
        [
            StructField("document_name", StringType(), nullable=True),
            StructField("folder_path", StringType(), nullable=True),
            StructField("study", StringType(), nullable=True),
            StructField("country", StringType(), nullable=True),
            StructField("site", StringType(), nullable=True),
            StructField("zone", StringType(), nullable=True),
            StructField("section", StringType(), nullable=True),
            StructField("artifact_#", StringType(), nullable=True),
            StructField("format", StringType(), nullable=True),
            StructField("created_on", StringType(), nullable=True),
            StructField("created_by", StringType(), nullable=True),
            StructField("document_title", StringType(), nullable=True),
            StructField("version", StringType(), nullable=True),
            StructField("updated_on", StringType(), nullable=True),
            StructField("uuid", StringType(), nullable=True),
        ]
    )

    ETMF_REJECTIONS_SCHEMA = StructType(
        [
            StructField("document_name", StringType(), nullable=True),
            StructField("folder_path", StringType(), nullable=True),
            StructField("rejected_date", StringType(), nullable=True),
            StructField("rejected_by", StringType(), nullable=True),
            StructField("rejection_reason", StringType(), nullable=True),
            StructField("comment", StringType(), nullable=True),
            StructField("open", StringType(), nullable=True),
            StructField("finalized_version", StringType(), nullable=True),
            StructField("finalized_document_state", StringType(), nullable=True),
            StructField("owner", StringType(), nullable=True),
            StructField("version", StringType(), nullable=True),
            StructField("study", StringType(), nullable=True),
            StructField("site", StringType(), nullable=True),
            StructField("uuid", StringType(), nullable=True),
        ]
    )

    TABLE_SCHEMAS = {
        "etmf_full_details": ETMF_FULL_DETAILS_SCHEMA,
        "etmf_filed_docs": ETMF_FILED_DOCS_SCHEMA,
        "etmf_rejections": ETMF_REJECTIONS_SCHEMA,
    }

    TABLE_METADATA = {
        "etmf_full_details": {
            "primary_keys": ["document_id", "fsi_uuid"],
            "cursor_field": "",
            "ingestion_type": "snapshot",
        },
        "etmf_filed_docs": {
            "primary_keys": ["document_name", "folder_path", "study", "uuid"],
            "cursor_field": "",
            "ingestion_type": "snapshot",
        },
        "etmf_rejections": {
            "primary_keys": ["document_name", "folder_path", "rejected_date", "uuid"],
            "cursor_field": "",
            "ingestion_type": "snapshot",
        },
    }


    class MedidataEtmfLakeflowConnect(LakeflowConnect):
        """LakeflowConnect implementation for Medidata eTMF.

        Authentication uses Medidata's MAuth protocol (request signing with
        RSA private key). Data is extracted from pre-generated Excel reports
        via a two-step API call pattern.
        """

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)

            app_uuid = options["app_uuid"]
            private_key = options["private_key"]
            self._client_division_scheme_uuid = options["client_division_scheme_uuid"]
            self._base_url = options.get("base_url", DEFAULT_BASE_URL).rstrip("/")

            self._mauth = MAuth(app_uuid, private_key)
            self._headers = {
                "Accept": "application/json",
                "Mcc-Version": "v2019-04-12",
            }

        # ------------------------------------------------------------------
        # HTTP helpers
        # ------------------------------------------------------------------

        def _request_with_retry(
            self, url: str, params: dict | None = None
        ) -> requests.Response:
            """Issue a GET request with MAuth signing and exponential backoff."""
            backoff = INITIAL_BACKOFF
            last_resp = None
            for attempt in range(MAX_RETRIES):
                resp = requests.get(
                    url,
                    auth=self._mauth,
                    headers=self._headers,
                    params=params,
                    timeout=REQUEST_TIMEOUT,
                )
                if resp.status_code not in RETRIABLE_STATUS_CODES:
                    return resp
                last_resp = resp
                if attempt < MAX_RETRIES - 1:
                    time.sleep(backoff)
                    backoff *= 2

            return last_resp  # type: ignore[return-value]

        # ------------------------------------------------------------------
        # Report discovery helpers
        # ------------------------------------------------------------------

        def _fetch_all_reports(
            self,
            created_at_from: int | None = None,
            created_at_to: int | None = None,
        ) -> list[dict]:
            """Fetch all report listings from ``GET /fetch_reports``.

            Args:
                created_at_from: Start of time window (epoch ms). If None, defaults
                    to start of first day of current month (00:00:00 UTC).
                created_at_to: End of time window (epoch ms). If None, defaults to
                    end of first day of current month (23:59:59 UTC).
            """
            from datetime import datetime, timezone

            if created_at_from is None:
                now = datetime.now(timezone.utc)
                start = datetime(now.year, now.month, 1, tzinfo=timezone.utc)
                created_at_from = int(start.timestamp() * 1000)
            if created_at_to is None:
                now = datetime.now(timezone.utc)
                end = datetime(now.year, now.month, 1, 23, 59, 59, tzinfo=timezone.utc)
                created_at_to = int(end.timestamp() * 1000)

            url = f"{self._base_url}/fetch_reports"
            params: dict = {
                "client_division_scheme_uuid": self._client_division_scheme_uuid,
                "show_obsoleted": False,
                "created_at_from": created_at_from,
                "created_at_to": created_at_to,
                "pageSize": DEFAULT_PAGE_SIZE,
                "pageStart": 0,
            }

            all_elements: list[dict] = []
            has_next_page = True

            while has_next_page:
                resp = self._request_with_retry(url, params=params)
                if resp.status_code != 200:
                    raise RuntimeError(
                        f"Failed to fetch reports: HTTP {resp.status_code} — {resp.text}"
                    )
                data = resp.json()
                children = data.get("children", {})
                all_elements.extend(children.get("elements", []))
                has_next_page = children.get("hasNextPage", False)
                params["pageStart"] = params["pageStart"] + params["pageSize"]

            return all_elements

        def _get_latest_report_uuids(
            self, reports: list[dict], report_type: str
        ) -> list[str]:
            """Filter reports by type, group by study, take latest by updatedAt."""
            if not reports:
                return []

            df = pd.DataFrame(reports)
            # Use non-capturing pattern for .str.contains (avoids group warning)
            filter_pattern = REPORT_NAME_PATTERN.pattern.replace("(", "(?:")
            matched = df[
                df["name"].str.contains(
                    filter_pattern, case=False, na=False, regex=True
                )
            ].copy()

            if matched.empty:
                return []

            matched["matched_study"] = matched["name"].str.extract(
                REPORT_NAME_PATTERN, expand=False
            )

            typed = matched[matched["systemFolderTypeLocalized"] == report_type].copy()
            if typed.empty:
                return []

            typed["updatedAt"] = pd.to_numeric(typed["updatedAt"], errors="coerce")
            typed = typed.sort_values(
                ["matched_study", "updatedAt"], ascending=[True, False]
            )
            latest = typed.groupby("matched_study", as_index=False).first()
            return latest["uuid"].tolist()

        def _download_report(self, fsi_uuid: str) -> pd.DataFrame:
            """Download a single report Excel file and parse as DataFrame."""
            url = f"{self._base_url}/regulated_files/{fsi_uuid}/content"
            params = {
                "client_division_scheme_uuid": self._client_division_scheme_uuid,
            }
            resp = self._request_with_retry(url, params=params)
            if resp.status_code != 200:
                raise RuntimeError(
                    f"Failed to download report {fsi_uuid}: "
                    f"HTTP {resp.status_code} — {resp.text}"
                )
            return pd.read_excel(BytesIO(resp.content), dtype=str)

        # ------------------------------------------------------------------
        # LakeflowConnect interface
        # ------------------------------------------------------------------

        def list_tables(self) -> list[str]:
            """Return the static list of supported tables."""
            return list(SUPPORTED_TABLES)

        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """Return the hard-coded Spark schema for the given table."""
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """Return metadata for the given table (all snapshot)."""
            self._validate_table(table_name)
            return dict(TABLE_METADATA[table_name])

        def read_table(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            """Read all records for a snapshot table.

            Fetches report listings, identifies the latest reports for the
            requested type, downloads each Excel file, and yields rows as dicts.
            """
            self._validate_table(table_name)
            report_type = TABLE_TO_REPORT_TYPE[table_name]

            # Allow callers to specify time window via table_options
            created_at_from = (
                int(table_options["created_at_from"])
                if "created_at_from" in table_options
                else None
            )
            created_at_to = (
                int(table_options["created_at_to"])
                if "created_at_to" in table_options
                else None
            )
            all_reports = self._fetch_all_reports(created_at_from, created_at_to)
            if not all_reports:
                return iter([]), {}

            uuids = self._get_latest_report_uuids(all_reports, report_type)
            if not uuids:
                return iter([]), {}

            records: list[dict] = []
            for fsi_uuid in uuids:
                try:
                    raw_df = self._download_report(fsi_uuid)
                except RuntimeError:
                    continue

                if raw_df.empty:
                    continue

                if table_name == "etmf_full_details":
                    available_cols = [
                        c for c in FULL_DETAILS_COLUMN_MAP if c in raw_df.columns
                    ]
                    subset = raw_df[available_cols].rename(
                        columns=FULL_DETAILS_COLUMN_MAP
                    )
                    subset["fsi_uuid"] = fsi_uuid
                    row_dicts = subset.where(subset.notna(), None).to_dict(
                        orient="records"
                    )
                else:
                    renamed = raw_df.rename(
                        columns=lambda x: x.lower().replace(" ", "_")
                    )
                    renamed["uuid"] = fsi_uuid
                    row_dicts = renamed.where(renamed.notna(), None).to_dict(
                        orient="records"
                    )

                records.extend(row_dicts)

            return iter(records), {}

        def _validate_table(self, table_name: str) -> None:
            """Raise ValueError if the table is not supported."""
            if table_name not in SUPPORTED_TABLES:
                raise ValueError(
                    f"Table \'\'{table_name}\'\'  is not supported. "
                    f"Supported tables: {SUPPORTED_TABLES}"
                )


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = MedidataEtmfLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"


    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]


    class LakeflowPartitionedStreamReader(DataSourceStreamReader):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def latestOffset(self):
            # PySpark does not pass the current offset to latestOffset() yet,
            # so we forward None.  Once PySpark supports it, pass the real value.
            return self.lakeflow_connect.latest_offset(self.table_name, self.table_options, None)

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name != METADATA_TABLE:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        """
        PySpark DataSource implementation for Lakeflow Connect.
        """

        def __init__(self, options):
            self.options = options
            # TEMPORARY: LakeflowConnectImpl is replaced with the actual implementation
            # class during merge. See the placeholder comment at the top of this file.
            self.lakeflow_connect = LakeflowConnectImpl(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
