# ==============================================================================
# Merged Lakeflow Source: survey_sparrow
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import Any, Iterator
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import DataSource, DataSourceReader, SimpleDataSourceStreamReader
from pyspark.sql.types import *
import base64
import urllib.error
import urllib.parse
import urllib.request


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/sources/survey_sparrow/survey_sparrow.py
    ########################################################

    _REGION_URLS: dict[str, str] = {
        "us":    "https://api.surveysparrow.com/v3",
        "eu":    "https://eu-api.surveysparrow.com/v3",
        "ap":    "https://ap-api.surveysparrow.com/v3",
        "me":    "https://me-api.surveysparrow.com/v3",
        "uk":    "https://eu-ln-api.surveysparrow.com/v3",
        "ap-sy": "https://ap-sy-api.surveysparrow.com/v3",
        "ca":    "https://ca-api.surveysparrow.com/v3",
    }

    _SUPPORTED_TABLES: list[str] = [
        "surveys",
        "responses",
        "questions",
        "contacts",
        "contact_lists",
        "contact_properties",
        "users",
        "roles",
        "teams",
        "survey_folders",
        "channels",
        "variables",
        "tickets",
        "audit_logs",
        "webhooks",
        "targets",
    ]

    # Tables that require a survey_id to be passed in table_options
    _SURVEY_PARTITIONED: set[str] = {"responses", "questions", "channels", "variables"}

    # ---------------------------------------------------------------------------
    # Static schemas
    # ---------------------------------------------------------------------------

    _ANSWER_SCHEMA = StructType([
        StructField("question",      StringType(),          True),
        StructField("question_tags", ArrayType(StringType()), True),
        StructField("question_id",   LongType(),            True),
        StructField("skipped",       BooleanType(),         True),
    ])

    _CHANNEL_EMBED_SCHEMA = StructType([
        StructField("name",   StringType(), True),
        StructField("type",   StringType(), True),
        StructField("status", StringType(), True),
    ])

    TABLE_SCHEMAS: dict[str, StructType] = {
        "surveys": StructType([
            StructField("id",                 LongType(),    False),
            StructField("name",               StringType(),  True),
            StructField("archived",           BooleanType(), True),
            StructField("survey_type",        StringType(),  True),
            StructField("created_at",         StringType(),  True),
            StructField("updated_at",         StringType(),  True),
            StructField("survey_folder_id",   LongType(),    True),
            StructField("survey_folder_name", StringType(),  True),
        ]),
        "responses": StructType([
            StructField("id",             LongType(),              False),
            StructField("survey_id",      LongType(),              True),
            StructField("contact_id",     LongType(),              True),
            StructField("completed",      StringType(),            True),
            StructField("channel_id",     LongType(),              True),
            StructField("language",       StringType(),            True),
            StructField("completed_time", StringType(),            True),
            StructField("answers",        StringType(),            True),  # JSON array
            StructField("channel",        StringType(),            True),  # JSON object
            StructField("contact",        StringType(),            True),  # JSON object/string
            StructField("expressions",    StringType(),            True),  # JSON array
        ]),
        "questions": StructType([
            StructField("id",                  LongType(),    False),
            StructField("type",                StringType(),  True),
            StructField("position",            StringType(),  True),
            StructField("hasDisplayLogic",     BooleanType(), True),
            StructField("properties",          StringType(),  True),  # JSON object
            StructField("survey_id",           LongType(),    True),
            StructField("section_id",          LongType(),    True),
            StructField("account_id",          LongType(),    True),
            StructField("parent_question_id",  LongType(),    True),
            StructField("choices",             StringType(),  True),  # JSON array
            StructField("annotations",         StringType(),  True),  # JSON array
            StructField("created_at",          StringType(),  True),
            StructField("is_required",         BooleanType(), True),
            StructField("multiple_answers",    BooleanType(), True),
        ]),
        "contacts": StructType([
            StructField("id",           LongType(),    False),
            StructField("active",       BooleanType(), True),
            StructField("email",        StringType(),  True),
            StructField("first_name",   StringType(),  True),
            StructField("last_name",    StringType(),  True),
            StructField("name",         StringType(),  True),
            StructField("job_title",    StringType(),  True),
            StructField("mobile",       StringType(),  True),
            StructField("unsubscribed", BooleanType(), True),
            StructField("createddate",  StringType(),  True),
        ]),
        "contact_lists": StructType([
            StructField("id",          LongType(),   False),
            StructField("name",        StringType(), True),
            StructField("description", StringType(), True),
            StructField("created_at",  StringType(), True),
        ]),
        "contact_properties": StructType([
            StructField("id",                       LongType(),   False),
            StructField("name",                     StringType(), True),
            StructField("label",                    StringType(), True),
            StructField("type",                     StringType(), True),
            StructField("description",              StringType(), True),
            StructField("contact_property_group_id", LongType(),  True),
            StructField("group",                    StringType(), True),
        ]),
        "users": StructType([
            StructField("id",            LongType(),    False),
            StructField("name",          StringType(),  True),
            StructField("email",         StringType(),  True),
            StructField("phone",         StringType(),  True),
            StructField("admin",         BooleanType(), True),
            StructField("owner",         BooleanType(), True),
            StructField("agency_owner",  BooleanType(), True),
            StructField("verified",      BooleanType(), True),
            StructField("role_id",       LongType(),    True),
            StructField("created_at",    StringType(),  True),
        ]),
        "roles": StructType([
            StructField("id",          LongType(),   False),
            StructField("name",        StringType(), True),
            StructField("label",       StringType(), True),
            StructField("description", StringType(), True),
            StructField("account_id",  LongType(),   True),
            StructField("created_at",  StringType(), True),
            StructField("updated_at",  StringType(), True),
            StructField("deleted_at",  StringType(), True),
        ]),
        "teams": StructType([
            StructField("id",                   LongType(),    False),
            StructField("name",                 StringType(),  True),
            StructField("description",          StringType(),  True),
            StructField("type",                 StringType(),  True),
            StructField("account_id",           LongType(),    True),
            StructField("business_hour_id",     LongType(),    True),
            StructField("round_robin_enabled",  BooleanType(), True),
            StructField("created_at",           StringType(),  True),
            StructField("updated_at",           StringType(),  True),
            StructField("deleted_at",           StringType(),  True),
        ]),
        "survey_folders": StructType([
            StructField("id",                      LongType(),   False),
            StructField("name",                    StringType(), True),
            StructField("description",             StringType(), True),
            StructField("auto_created",            BooleanType(), True),
            StructField("visibility",              StringType(), True),
            StructField("teams",                   StringType(), True),  # JSON array of ints
            StructField("users",                   StringType(), True),  # JSON array of ints
            StructField("surveys",                 StringType(), True),  # JSON array of objects
            StructField("parent_survey_folder_id", LongType(),   True),
            StructField("subfolders",              StringType(), True),  # JSON array
            StructField("echoes",                  StringType(), True),  # JSON array
            StructField("created_at",              StringType(), True),
        ]),
        "channels": StructType([
            StructField("id",         LongType(),   False),
            StructField("survey_id",  LongType(),   True),
            StructField("name",       StringType(), True),
            StructField("status",     StringType(), True),
            StructField("type",       StringType(), True),
            StructField("properties", StringType(), True),  # JSON object
        ]),
        "variables": StructType([
            StructField("id",          LongType(),   False),
            StructField("survey_id",   LongType(),   True),
            StructField("label",       StringType(), True),
            StructField("name",        StringType(), True),
            StructField("description", StringType(), True),
            StructField("type",        StringType(), True),
        ]),
        "tickets": StructType([
            StructField("id",                   LongType(),   False),
            StructField("requester",            StringType(), True),  # JSON object
            StructField("subject",              StringType(), True),
            StructField("description",          StringType(), True),
            StructField("description_html",     StringType(), True),
            StructField("priority",             StringType(), True),  # JSON object
            StructField("status",               StringType(), True),  # JSON object
            StructField("template_id",          LongType(),   True),
            StructField("custom_fields",        StringType(), True),  # JSON object
            StructField("source",               StringType(), True),  # JSON object
            StructField("agent",                StringType(), True),  # JSON object
            StructField("team",                 StringType(), True),  # JSON object
            StructField("created_at",           StringType(), True),
            StructField("updated_at",           StringType(), True),
            StructField("deleted_at",           StringType(), True),
            StructField("first_response_due",   StringType(), True),
            StructField("resolution_due",       StringType(), True),
        ]),
        "audit_logs": StructType([
            StructField("id",         StringType(), False),  # UUID string
            StructField("object",     StringType(), True),
            StructField("event",      StringType(), True),
            StructField("operation",  StringType(), True),
            StructField("device",     StringType(), True),
            StructField("ipAddress",  StringType(), True),
            StructField("time",       StringType(), True),
            StructField("actor",      StringType(), True),  # JSON object
            StructField("message",    StringType(), True),
        ]),
        "webhooks": StructType([
            StructField("id",                      LongType(),    False),
            StructField("name",                    StringType(),  True),
            StructField("url",                     StringType(),  True),
            StructField("eventType",               StringType(),  True),
            StructField("description",             StringType(),  True),
            StructField("objectType",              StringType(),  True),
            StructField("httpMethod",              StringType(),  True),
            StructField("headers",                 StringType(),  True),  # JSON array
            StructField("properties",              StringType(),  True),  # JSON object
            StructField("payload",                 StringType(),  True),
            StructField("includePartialSubmission", BooleanType(), True),
            StructField("disabled",                BooleanType(), True),
        ]),
        "targets": StructType([
            StructField("targets", StringType(), True),  # JSON array of strings
            StructField("page",    LongType(),   True),
            StructField("count",   LongType(),   True),
        ]),
    }

    # ---------------------------------------------------------------------------
    # Per-table ingestion metadata
    # ---------------------------------------------------------------------------

    _TABLE_METADATA: dict[str, dict] = {
        "surveys":            {"ingestion_type": "cdc",      "primary_keys": ["id"], "cursor_field": "updated_at"},
        "responses":          {"ingestion_type": "cdc",      "primary_keys": ["id"], "cursor_field": "completed_time"},
        "questions":          {"ingestion_type": "snapshot", "primary_keys": ["id"], "cursor_field": None},
        "contacts":           {"ingestion_type": "cdc",      "primary_keys": ["id"], "cursor_field": "createddate"},
        "contact_lists":      {"ingestion_type": "snapshot", "primary_keys": ["id"], "cursor_field": None},
        "contact_properties": {"ingestion_type": "snapshot", "primary_keys": ["id"], "cursor_field": None},
        "users":              {"ingestion_type": "snapshot", "primary_keys": ["id"], "cursor_field": None},
        "roles":              {"ingestion_type": "snapshot", "primary_keys": ["id"], "cursor_field": None},
        "teams":              {"ingestion_type": "snapshot", "primary_keys": ["id"], "cursor_field": None},
        "survey_folders":     {"ingestion_type": "snapshot", "primary_keys": ["id"], "cursor_field": None},
        "channels":           {"ingestion_type": "snapshot", "primary_keys": ["id"], "cursor_field": None},
        "variables":          {"ingestion_type": "snapshot", "primary_keys": ["id"], "cursor_field": None},
        "tickets":            {"ingestion_type": "cdc",      "primary_keys": ["id"], "cursor_field": "updated_at"},
        "audit_logs":         {"ingestion_type": "append",   "primary_keys": ["id"], "cursor_field": "time"},
        "webhooks":           {"ingestion_type": "snapshot", "primary_keys": ["id"], "cursor_field": None},
        "targets":            {"ingestion_type": "snapshot", "primary_keys": [],     "cursor_field": None},
    }

    # Retry config
    _INITIAL_BACKOFF = 1.0
    _MAX_RETRIES = 4
    _RETRIABLE_CODES = {429, 500, 502, 503, 504}
    _LOOKBACK_SECONDS = 60
    _DEFAULT_WINDOW_SECONDS = 3600  # Strategy A default: 1-hour sliding window


    # ---------------------------------------------------------------------------
    # Connector
    # ---------------------------------------------------------------------------

    class SurveySparrowLakeflowConnect(LakeflowConnect):
        """LakeflowConnect implementation for the SurveySparrow V3 REST API."""

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)
            self._token = options["access_token"]
            region = options.get("region", "us").lower()
            self._base_url = _REGION_URLS.get(region, _REGION_URLS["us"])
            # Cap cursors at init time to prevent chasing actively written data.
            self._init_ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"
            self._lookback_applied: set[str] = set()

        # -----------------------------------------------------------------------
        # Interface implementation
        # -----------------------------------------------------------------------

        def list_tables(self) -> list[str]:
            return _SUPPORTED_TABLES.copy()

        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            self._validate_table(table_name)
            meta = _TABLE_METADATA[table_name]
            result: dict = {
                "primary_keys": meta["primary_keys"],
                "ingestion_type": meta["ingestion_type"],
            }
            if meta["ingestion_type"] in ("cdc", "append") and meta["cursor_field"]:
                result["cursor_field"] = meta["cursor_field"]
            return result

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            self._validate_table(table_name)
            ingestion_type = _TABLE_METADATA[table_name]["ingestion_type"]

            if ingestion_type == "snapshot":
                return self._read_snapshot(table_name, table_options)
            elif ingestion_type == "append":
                return self._read_append(table_name, start_offset, table_options)
            else:  # cdc
                return self._read_cdc(table_name, start_offset, table_options)

        # -----------------------------------------------------------------------
        # Snapshot read
        # -----------------------------------------------------------------------

        def _read_snapshot(
            self, table_name: str, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Full-refresh: paginate all pages and return offset={}."""
            if table_name in _SURVEY_PARTITIONED:
                records = self._read_survey_partitioned_snapshot(table_name, table_options)
            else:
                records = self._paginate_all(table_name, {})
            return iter(records), {}

        def _read_survey_partitioned_snapshot(
            self, table_name: str, table_options: dict[str, str]
        ) -> list[dict]:
            """Read a survey-partitioned table.  If survey_id provided use it;
            otherwise iterate over all surveys."""
            survey_ids = self._resolve_survey_ids(table_options)
            records: list[dict] = []
            for sid in survey_ids:
                batch = self._paginate_all(table_name, {"survey_id": str(sid)})
                for rec in batch:
                    rec["survey_id"] = sid
                records.extend(batch)
            return records

        # -----------------------------------------------------------------------
        # CDC read
        # -----------------------------------------------------------------------

        def _read_cdc(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Incremental CDC read bounded by max_records_per_batch."""
            cursor_field = _TABLE_METADATA[table_name]["cursor_field"]
            since = start_offset.get("cursor") if start_offset else None

            # Short-circuit: already caught up to init time.
            if since and since >= self._init_ts:
                return iter([]), start_offset

            # Apply lookback once per trigger per table.
            effective_since = since
            if since and table_name not in self._lookback_applied:
                self._lookback_applied.add(table_name)
                dt = datetime.fromisoformat(since.replace("Z", "+00:00"))
                effective_since = (dt - timedelta(seconds=_LOOKBACK_SECONDS)).isoformat()

            # Strategy A: bounded sliding time-window (only when a starting cursor exists).
            until: str | None = None
            if effective_since:
                window_secs = int(table_options.get("window_seconds", str(_DEFAULT_WINDOW_SECONDS)))
                dt_since = datetime.fromisoformat(effective_since.replace("Z", "+00:00"))
                dt_until = dt_since + timedelta(seconds=window_secs)
                dt_init = datetime.fromisoformat(self._init_ts.replace("Z", "+00:00"))
                if dt_until > dt_init:
                    dt_until = dt_init
                until = dt_until.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"

            max_records = int(table_options.get("max_records_per_batch", "200"))

            if table_name in _SURVEY_PARTITIONED:
                records = self._read_cdc_survey_partitioned(
                    table_name, effective_since, until, table_options, max_records
                )
            else:
                params = self._build_cdc_params(table_name, effective_since, until)
                records = []
                page = 1
                while len(records) < max_records:
                    params["page"] = str(page)
                    params["limit"] = str(
                        min(self._page_limit(table_name), max_records - len(records))
                    )
                    batch, has_next = self._fetch_page(table_name, params)
                    if not batch:
                        break
                    records.extend(batch)
                    if not has_next:
                        break
                    page += 1

            if not records:
                # Advance the cursor to the window end so the next call slides forward.
                if until:
                    return iter([]), {"cursor": until}
                return iter([]), start_offset or {}

            last_cursor = records[-1].get(cursor_field, "")
            end_offset = {"cursor": last_cursor}
            if start_offset and start_offset == end_offset:
                return iter([]), start_offset
            return iter(records), end_offset

        def _read_cdc_survey_partitioned(
            self,
            table_name: str,
            since: str | None,
            until: str | None,
            table_options: dict[str, str],
            max_records: int,
        ) -> list[dict]:
            survey_ids = self._resolve_survey_ids(table_options)
            cursor_field = _TABLE_METADATA[table_name]["cursor_field"]
            records: list[dict] = []
            for sid in survey_ids:
                if len(records) >= max_records:
                    break
                params = self._build_cdc_params(table_name, since, until)
                params["survey_id"] = str(sid)
                page = 1
                while len(records) < max_records:
                    params["page"] = str(page)
                    params["limit"] = str(
                        min(self._page_limit(table_name), max_records - len(records))
                    )
                    batch, has_next = self._fetch_page(table_name, params)
                    if not batch:
                        break
                    for rec in batch:
                        rec["survey_id"] = sid
                    records.extend(batch)
                    if not has_next:
                        break
                    page += 1
            return records

        # -----------------------------------------------------------------------
        # Append read (audit_logs)
        # -----------------------------------------------------------------------

        def _read_append(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Append-only read for audit_logs.  Uses server-side limit to avoid
            cutting mid-page (no client-side truncation)."""
            cursor_field = _TABLE_METADATA[table_name]["cursor_field"]
            since = start_offset.get("cursor") if start_offset else None

            if since and since >= self._init_ts:
                return iter([]), start_offset

            limit = int(table_options.get("limit", "100"))
            max_records = int(table_options.get("max_records_per_batch", "200"))

            params: dict[str, str] = {"limit": str(min(limit, 500))}
            if since:
                params["start_date"] = since

            records: list[dict] = []
            page = 1
            while len(records) < max_records:
                params["page"] = str(page)
                batch, has_next = self._fetch_page(table_name, params)
                if not batch:
                    break
                # For audit_logs, API returns records under "list" key; _fetch_page handles this
                records.extend(batch)
                # For append: process full pages, stop after max_records threshold is reached
                if len(records) >= max_records:
                    break
                if not has_next:
                    break
                page += 1

            if not records:
                return iter([]), start_offset or {}

            last_cursor = records[-1].get(cursor_field, "")
            end_offset = {"cursor": last_cursor}
            if start_offset and start_offset == end_offset:
                return iter([]), start_offset
            return iter(records), end_offset

        # -----------------------------------------------------------------------
        # HTTP helpers
        # -----------------------------------------------------------------------

        def _get(
            self, path: str, params: dict[str, str] | None = None
        ) -> dict:
            """Make a GET request with retry on transient errors."""
            url = self._base_url + path
            if params:
                url += "?" + urllib.parse.urlencode(params)

            backoff = _INITIAL_BACKOFF
            last_exc: Exception | None = None
            for attempt in range(_MAX_RETRIES):
                req = urllib.request.Request(
                    url, headers={"Authorization": f"Bearer {self._token}"}
                )
                try:
                    with urllib.request.urlopen(req, timeout=20) as resp:
                        return json.loads(resp.read().decode())
                except urllib.error.HTTPError as exc:
                    if exc.code not in _RETRIABLE_CODES:
                        raise
                    last_exc = exc
                except OSError as exc:
                    last_exc = exc
                if attempt < _MAX_RETRIES - 1:
                    time.sleep(backoff)
                    backoff = min(backoff * 2, 30)

            raise RuntimeError(f"Request failed after {_MAX_RETRIES} attempts: {last_exc}")

        def _fetch_page(
            self, table_name: str, params: dict[str, str]
        ) -> tuple[list[dict], bool]:
            """Fetch one page for table_name and return (records, has_next_page)."""
            path = _table_path(table_name)
            body = self._get(path, params)

            # audit_logs uses "list" key; all others use "data"
            if table_name == "audit_logs":
                records = body.get("list", [])
            elif table_name == "targets":
                # targets wraps results under data.targets
                inner = body.get("data", {})
                if isinstance(inner, dict):
                    raw_targets = inner.get("targets", [])
                    has_next = inner.get("has_next_page", False)
                    return [{"targets": json.dumps(raw_targets),
                             "page":    inner.get("page"),
                             "count":   inner.get("count")}], has_next
                records = []
            else:
                records = body.get("data", [])

            # Serialize complex fields
            records = [_serialize_complex(r) for r in records]
            has_next = body.get("has_next_page", False)
            return records, has_next

        def _paginate_all(
            self, table_name: str, extra_params: dict[str, str]
        ) -> list[dict]:
            """Paginate a snapshot table until has_next_page is False."""
            records: list[dict] = []
            page = 1
            limit = self._page_limit(table_name)
            while True:
                params = {"page": str(page), "limit": str(limit), **extra_params}
                batch, has_next = self._fetch_page(table_name, params)
                records.extend(batch)
                if not has_next:
                    break
                page += 1
            return records

        # -----------------------------------------------------------------------
        # Helpers
        # -----------------------------------------------------------------------

        def _validate_table(self, table_name: str) -> None:
            if table_name not in _SUPPORTED_TABLES:
                raise ValueError(
                    f"Table '{table_name}' is not supported. "
                    f"Supported tables: {_SUPPORTED_TABLES}"
                )

        def _resolve_survey_ids(self, table_options: dict[str, str]) -> list[int]:
            """Return survey IDs from table_options, or fetch all surveys if not provided."""
            raw = table_options.get("survey_id", "")
            if raw:
                # Accept comma-separated or single id
                return [int(s.strip()) for s in raw.split(",") if s.strip()]
            # Fallback: list all surveys
            all_surveys = self._paginate_all("surveys", {})
            return [s["id"] for s in all_surveys if s.get("id")]

        @staticmethod
        def _build_cdc_params(
            table_name: str, since: str | None, until: str | None = None
        ) -> dict[str, str]:
            """Build query params for an incremental read on table_name.

            Supports Strategy A: when ``until`` is provided it adds the matching
            upper-bound filter so the server scans only a bounded time window.
            """
            params: dict[str, str] = {}
            if since:
                if table_name == "surveys":
                    params["updated_date.gte"] = since
                    if until:
                        params["updated_date.lte"] = until
                elif table_name == "responses":
                    params["date.gte"] = since
                    if until:
                        params["date.lte"] = until
                    params["order_by"] = "completedTime"
                    params["order"] = "ASC"
                elif table_name == "contacts":
                    params["created_date.gte"] = since
                    if until:
                        params["created_date.lte"] = until
                elif table_name == "tickets":
                    params["updated_date.gte"] = _fmt_ticket_ts(since)
                    if until:
                        params["updated_date.lte"] = _fmt_ticket_ts(until)
            return params

        @staticmethod
        def _page_limit(table_name: str) -> int:
            _limits: dict[str, int] = {
                "surveys": 100,
                "responses": 200,
                "questions": 100,
                "contacts": 50,
                "users": 50,
                "roles": 100,
                "teams": 100,
                "survey_folders": 100,
                "channels": 100,
                "variables": 100,
                "tickets": 100,
                "audit_logs": 500,
                "webhooks": 100,
                "targets": 200,
                "contact_lists": 50,
                "contact_properties": 50,
            }
            return _limits.get(table_name, 50)


    # ---------------------------------------------------------------------------
    # Module-level helpers
    # ---------------------------------------------------------------------------


    def _fmt_ticket_ts(ts: str) -> str:
        """Normalise a timestamp to the format expected by the tickets API: YYYY-MM-DDTHH:MM:SS."""
        dt = datetime.fromisoformat(ts.replace("Z", "+00:00"))
        return dt.strftime("%Y-%m-%dT%H:%M:%S")


    def _table_path(table_name: str) -> str:
        """Map table name to API path segment."""
        _paths: dict[str, str] = {
            "surveys":            "/surveys",
            "responses":          "/responses",
            "questions":          "/questions",
            "contacts":           "/contacts",
            "contact_lists":      "/contact_lists",
            "contact_properties": "/contact_properties",
            "users":              "/users",
            "roles":              "/roles",
            "teams":              "/teams",
            "survey_folders":     "/survey_folders",
            "channels":           "/channels",
            "variables":          "/variables",
            "tickets":            "/tickets",
            "audit_logs":         "/audit_logs",
            "webhooks":           "/webhooks",
            "targets":            "/targets",
        }
        return _paths[table_name]


    _COMPLEX_FIELDS: set[str] = {
        "answers", "channel", "contact", "expressions",
        "properties", "choices", "annotations",
        "requester", "priority", "status", "custom_fields", "source", "agent", "team",
        "actor",
        "headers",
        "teams", "users", "surveys", "subfolders", "echoes",
    }


    def _serialize_complex(record: dict) -> dict:
        """JSON-serialize any dict/list fields so Spark sees them as StringType."""
        result = {}
        for k, v in record.items():
            if k in _COMPLEX_FIELDS and isinstance(v, (dict, list)):
                result[k] = json.dumps(v)
            else:
                result[k] = v
        return result


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = SurveySparrowLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"


    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]

        def read(self, partition):
            all_records = []
            if self.table_name == METADATA_TABLE:
                all_records = self._read_table_metadata()
            else:
                all_records, _ = self.lakeflow_connect.read_table(
                    self.table_name, None, self.options
                )

            rows = map(lambda x: parse_value(x, self.schema), all_records)
            return iter(rows)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        """
        PySpark DataSource implementation for Lakeflow Connect.
        """

        def __init__(self, options):
            self.options = options
            # TEMPORARY: LakeflowConnectImpl is replaced with the actual implementation
            # class during merge. See the placeholder comment at the top of this file.
            self.lakeflow_connect = LakeflowConnectImpl(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
